[package]
name = "graveler"
version = "0.1.0"
edition = "2021"

#[build]
#rustflags = ["-C", "target-cpu=native"]

[profile.release]
lto = "fat"
#codegen-units = 1

[dependencies]
rand = "0.8.5"
rayon = "1.10.0"
