[package]
name = "graveler"
version = "2.0.0"
edition = "2021"

[dev-dependencies]
#criterion = { version = "0.5", features = ["html_reports"] }
criterion = "0.5"

[[bench]]
name = "bernoulli"
harness = false

[[bin]]
harness = false
name = "graveler"

#[lib]
#crate-type = ["cdylib", "rlib"]

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"

[dependencies]
rayon = "1.10.0"
cached = "0.54.0"
rand = { version = "0.8.5", features = ["small_rng"] }
